zookeeper.connect-string=192.168.220.71:2181
kafka.bootstrap.servers=192.168.220.71:9092
###############
## JDBC URLS ##
###############
%oracle.database.jdbc.scdb.url=jdbc:oracle:thin:@192.168.220.70:1521/safewatch
%oracle.database.jdbc.filtering.url=jdbc:oracle:thin:@192.168.220.70:1521/safewatch
####################
## DB CREDENTIALS ##
####################
%oracle.quarkus.datasource."scdbPU".username=scdb
%oracle.quarkus.datasource."scdbPU".password=47d65070cc33c31965ab8b61faf8078c
%oracle.quarkus.datasource."filteringPU".username=swserver
%oracle.quarkus.datasource."filteringPU".password=47d65070cc33c31965ab8b61faf8078c
######################
## Optionnal Config ##
######################
# change the listening ip or port
# quarkus.http.host=
# quarkus.http.port=

# change the consumer group id as it has to be unique by service replica 
# mp.messaging.incoming.sws-interservice-in.group.id=

# kafka encryption settings
# kafka.security.protocol=SSL
# kafka.ssl.truststore.location=/tmp/ca.p12
# kafka.ssl.truststore.password=
# kafka.ssl.truststore.password.plain=${SWS_TRUST_PWD}
# kafka.ssl.keystore.location=/tmp/user.p12
# kafka.ssl.keystore.password=
# kafka.ssl.keystore.password.plain=${SWS_KEY_PWD}

# kafka incoming topic configuration
# mp.messaging.incoming.sws-interservice-in.topic=sws\.interservice.*
# mp.messaging.incoming.sws-interservice-in.pattern=true

# Quarkus based services logging rotation file configuration handler
# quarkus.log.file.enable=true

##############################################
## DO NOT MAKE MODIFICATION UNDER THIS LINE ##
##############################################
%oracle.database.db-kind=oracle
%oracle.quarkus.hibernate-orm."filteringPU".log.sql=false
%oracle.quarkus.hibernate-orm."scdbPU".log.sql=false
